package espoo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

// Tänne vois tehdä Thymeleaf version
@org.springframework.stereotype.Controller
public class Controller2 {

    @Autowired
    // This means to get the bean called RaakaaineRepository which is auto-generated by Spring, we will use it to handle the data
    private RaakaaineRepository sapuskarepo;

    @GetMapping(path = "/lounaslista")
    public @ResponseBody
    Iterable<Ruoka> haeSafkat() {
        return sapuskarepo.findAll();
    }

    @RequestMapping(path = "/lounas")
    public String viikonMatot(Model model) {

        model.addAttribute("paivat", sapuskarepo.findAll());

        return "eka_thyme";
    }


}
